const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({ channel: process.env.BROWSER_CHANNEL || undefined, headless: true });
  const base = 'http://127.0.0.1:4000/ics-lab-portal';
  try {
    const page = await browser.newPage({ reducedMotion: 'reduce' });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(`${base}/publications/`, { waitUntil: 'networkidle' });
    assert.equal(await page.locator('.publication-item').count(), 87);
    await page.locator('[data-filter-toggle]').click();
    await page.locator('button[data-track="Conference"]').click();
    const count = await page.locator('.publication-item:visible').count();
    assert(count > 0 && count < 87);
    await page.locator('button[data-track="All"]').click();
    assert.equal(await page.locator('.publication-item:visible').count(), 87);
    await page.locator('[data-language-toggle]:visible').click();
    assert.equal(await page.locator('html').getAttribute('lang'), 'zh');
    await page.locator('[data-theme-toggle]').click();
    assert(await page.locator('html').evaluate(node => node.classList.contains('dark')));
    const response = page.waitForResponse(url => url.url().endsWith('/search-index.json'));
    await page.locator('[data-search-open]').click();
    await response;
    await page.locator('[data-search-input]').fill('Baro2Talk');
    await page.locator('[data-search-results] a').first().waitFor();
    await page.keyboard.press('Escape');
    await page.waitForFunction(() => !document.querySelector('dialog[open]'));
    assert.equal(await page.locator('dialog[open]').count(), 0);
    await page.goto(`${base}/members/`, { waitUntil: 'networkidle' });
    assert.equal(await page.locator('[data-member]').count(), 14);
    assert.equal(await page.locator('[data-bio-open]').count(), 3);
    await page.locator('[data-bio-open]').first().click();
    assert.equal(await page.locator('dialog[open]').count(), 1);
    await page.keyboard.press('Escape');
    await page.goto(`${base}/#/publications/infocom2026-baro2talk`, { waitUntil: 'networkidle' });
    await page.waitForURL(`${base}/publications/infocom2026-baro2talk/`);
    await page.locator('[data-citation-open]').click();
    const bibtex = await page.locator('[data-citation-text]').innerText();
    assert.match(bibtex, /^@inproceedings\{/);
    assert.match(bibtex, /title=\{Baro2Talk/);
    assert.match(bibtex, /year=\{2026\}/);
    await page.context().grantPermissions(['clipboard-read', 'clipboard-write']);
    await page.locator('[data-copy-citation]').last().click();
    await page.waitForFunction(() => [...document.querySelectorAll('[data-copy-citation]')].some(button => button.textContent === '已复制'));
    assert.equal(await page.evaluate(() => navigator.clipboard.readText()), bibtex.trim());
    await page.keyboard.press('Escape');
    await page.goto(`${base}/gallery/`, { waitUntil: 'networkidle' });
    await page.locator('[data-album-open]').first().click();
    await page.locator('[data-album-view]:visible [data-lightbox-src]').first().click();
    assert.equal(await page.locator('dialog[open]').count(), 1);
    await page.locator('[data-lightbox-content] img').waitFor();
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('dialog[open]').count(), 0);
    await page.locator('[data-album-view]:visible [data-album-back]').click();
    await page.setViewportSize({ width: 390, height: 844 });
    await page.locator('[data-menu-toggle]').click();
    await page.locator('[data-mobile-menu] a').first().waitFor();
    assert.equal(await page.locator('[data-language-toggle]:visible').count(), 1);
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    assert.equal(errors.length, 0, errors.join('\n'));
    console.log('PASS: publications/filter, language/theme, search, 14 members/3 bios, old hash URL, BibTeX clipboard, gallery Escape/back, mobile navigation.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
